let num1 = 7;
let num2 = 6;
let add = num1 + num2;
let sub = num1 - num2;
let mult = num1 * num2;
let div = num1 / num2;
console.log("First Number:" , num1);
console.log("Second Number:" , num2);
console.log("Addition is:" , add);
console.log("Subtraction is:" , sub);
console.log("Multiplication is:" , mult);
console.log("Division is:" , div);